name: CI/CD pour BobApp

on:
  push:
    branches: [ main, dev/* ]
  pull_request:
    branches: [ main, dev/* ]

jobs:
  backend-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Tests and build with Maven
        run: mvn -B clean install
        working-directory: ./back

      - name: Upload backend report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jacoco-report
          path: back/target/site/jacoco

      - name: Upload compiled classes for SonarCloud
        uses: actions/upload-artifact@v4
        with:
          name: backend-target
          path: back/target

  frontend-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: front/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: ./front

      - name: Run Unit tests
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadless --code-coverage
        working-directory: ./front

      - name: Upload frontend report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: angular-coverage-report
          path: front/coverage

      - name: Build frontend
        run: npm run build
        working-directory: ./front


  sonarcloud-analysis:
    name: SonarCloud Analysis
    needs: [ backend-job, frontend-job ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./reports

      - name: Restore backend target directory
        run: |
          mkdir -p back/target
          cp -r reports/backend-target/* back/target/

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}